name: 'Test cherry-picking commits into branch'
description: 'Tests whether a set of commits can be cherry-picked onto a branch, e.g. PR commits against a release branch.'
author: 'Benedikt Ziemons'
inputs:
  work_dir:
    description: 'The path to the git working directory'
    required: true
    default: ${{ github.workspace }}
  target_remote:
    description: 'Repository name with owner for the target branch. For example, actions/checkout'
    required: true
    default: ${{ github.repository }}
  target_branch:
    description: 'Target branch for the test'
    required: true
    default: master
  source_remote_name:
    description: 'Remote name to use to be used in the source-commits ref, if necessary'
    required: true
    default: ${{ github.actor }}
  source_remote:
    description: 'Repository name with owner for the source-commits. For example, actions/checkout'
    required: true
    default: ${{ github.repository }}
  source_commits:
    description: 'Source commits for the test'
    required: true
    default: 'master..${{ github.ref }}'
runs:
  using: 'docker'
  image: 'Dockerfile'
