name: Daily image cache build for autotests

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 3 * * 1-5'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Identify branches
        id: branches
        run: echo "::set-output name=branches::$(echo "${{ github.event.repository.branches_url }}" | ./tools/github/workflow/grabrelease.py --all --json --add master)"
    outputs:
      branches: ${{ steps.branches.outputs.branches }}
  build_autotests:
    runs-on: ubuntu-latest
    needs:
      - setup
    strategy:
      matrix:
        branch: ${{ fromJson(needs.setup.outputs.branches) }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - name: Update pip
        run: python3 -m pip install -U pip setuptools
      - name: Install python requirements for matrix_parser.py
        run: python3 -m pip install -U PyYAML
      - name: Identify Matrix
        id: matrix
        run: echo "::set-output name=matrix::$(./tools/test/matrix_parser.py < ./etc/docker/test/matrix.yml)"
      - name: Build and upload images
        id: images
        shell: bash
        run: |
          docker login https://docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          i=0; until [ "$i" -ge 3 ]; do
            IMAGES=$(echo '${{ steps.matrix.outputs.matrix }}' | ./tools/test/build_images.py --output list \
                --build-no-cache --cache-repo docker.pkg.github.com/${{ github.repository }} --push-cache \
                --branch "${{ matrix.branch }}" ./etc/docker/test || echo "")
            if [[ -n $IMAGES ]]; then break;
            else
              i=$((i+1)); sleep 5;
              echo "::warning::Building images failed, retrying…"
            fi
          done
          docker logout https://docker.pkg.github.com
          if [[ -z $IMAGES ]]; then echo "::error::Building images failed ultimately"; exit 1; fi
  build_integration_tests:
    runs-on: ubuntu-latest
    needs:
      - setup
    strategy:
      matrix:
        branch: ${{ fromJson(needs.setup.outputs.branches) }}
    steps:
      - name: Checkout rucio containers repository
        uses: actions/checkout@v2
        with:
          repository: rucio/containers
      - name: Checkout rucio source
        uses: actions/checkout@v2
        with:
          path: dev/rucio
      - name: Update pip
        run: python3 -m pip install -U pip setuptools
      - name: Install python requirements for matrix_parser.py
        run: python3 -m pip install -U PyYAML
      - name: Identify Matrix
        id: matrix
        run: echo "::set-output name=matrix::$(${{ github.workspace }}/dev/rucio/tools/test/matrix_parser.py < ${{ github.workspace }}/dev/rucio/etc/docker/test/matrix_integration_tests.yml)"
      - name: Build and upload images
        id: images
        shell: bash
        run: |
          docker login https://docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          i=0; until [ "$i" -ge 3 ]; do
            IMAGES=$(echo '${{ steps.matrix.outputs.matrix }}' | ${{ github.workspace }}/dev/rucio/tools/test/build_images.py --output list \
                --build-no-cache --cache-repo docker.pkg.github.com/${{ github.repository }} --push-cache \
                --branch "${{ matrix.branch }}" ${{ github.workspace }}/dev || echo "")
            if [[ -n $IMAGES ]]; then break;
            else
              i=$((i+1)); sleep 5;
              echo "::warning::Building images failed, retrying…"
            fi
          done
          docker logout https://docker.pkg.github.com
          if [[ -z $IMAGES ]]; then echo "::error::Building images failed ultimately"; exit 1; fi