name: Pull request test release branch merge

on:
  pull_request:
    branches: [ next ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Log pull request event workload
      run: 'jq .pull_request._links.commits.href test.json | xargs curl | jq .\[\].sha | python -c ''import sys; print("::set-output name=source_commits::" + (lambda l: l[0] if len(l) == 1 else f"{l[0]}..{l[-1]}")(list(map(lambda l: l.rstrip().strip("\""), sys.stdin.readlines()))))'''
    - uses: bziemons/mergetest-docker-action@master
      with:
        target_branch: master
