name: Test PR into release

on:
  pull_request:
    branches: [ next ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch pull request commit range
        id: prcommits
        run: 'jq .pull_request._links.commits.href ${{ github.event_path }} | xargs curl | jq .\[\].sha | python3 -c ''import sys; print("::set-output name=source_commits::" + (lambda l: l[0] if len(l) == 1 else f"{l[0]}^..{l[-1]}")(list(map(lambda l: l.rstrip().strip("\""), sys.stdin.readlines()))))'''
      - uses: ./.github/actions/mergetest-docker-action
        with:
          source_commits: ${{ steps.prcommits.outputs.source_commits }}
          target_branch: master
      - name: Fetch containers repository and fetch or build images
        run: |
          git clone https://github.com/rucio/containers.git ./containers
          tar cf ./containers/dev/rucio.tar --exclude=containers *
          echo "rucio.tar packed for container image"
          sed -i 's/^RUN git clone https:\/\/github.com\/rucio\/rucio.git \/tmp\/rucio/ADD rucio.tar \/tmp\/rucio/' ./containers/dev/Dockerfile
          echo "replaced git clone with adding rucio.tar in rucio dev Dockerfile"
          sed -i 's/image: rucio\/rucio-dev/build: ..\/..\/..\/containers\/dev/' ./etc/docker/dev/docker-compose-storage.yml
          echo "replaced image with build context in docker-compose-storage.yml"
          docker-compose --file etc/docker/dev/docker-compose-storage.yml build --pull --no-cache
          echo "built and fetched images for docker-compose-storage.yml"
      - name: Run docker-compose-storage composition
        run: 'docker-compose --file etc/docker/dev/docker-compose-storage.yml up -d'
      - name: Run tests with docker
        run: 'docker-compose --file etc/docker/dev/docker-compose-storage.yml exec rucio tools/run_tests_docker.sh -r'
